custom: ["https://theeprc.org/donations-friends/" #EPRC, "https://www.buddhistgeeks.org/about" #Buddhist Geeks, "https://cbs.arizona.edu/news/visit-sema-lab-shinzen-young"] #SEMA Lab (Shinzen Young)]

